# Generated by Django 3.2.7 on 2023-04-29 18:18

from django.db import migrations, models
import django.db.models.deletion
import game.utils


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='on_vote',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(default=game.utils.generate_game_code, editable=False, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='gamemember',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='final_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.deckcard', verbose_name='Финальная оценка'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.issue', verbose_name='Задача'),
        ),
        migrations.AddConstraint(
            model_name='gamemember',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_game_user'),
        ),
    ]
